// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PoPs.Specs.Features.Users
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UserShouldBeAbleToGetANewPasswordFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ForgotPasswordFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "User should be able to get a new password", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "User should be able to get a new password")))
            {
                PoPs.Specs.Features.Users.UserShouldBeAbleToGetANewPasswordFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Try to reset password with empty email")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User should be able to get a new password")]
        public virtual void TryToResetPasswordWithEmptyEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Try to reset password with empty email", new string[] {
                        "ResetForEachTest"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("navigate to \'\'");
#line 6
 testRunner.And("click in the link login");
#line 7
 testRunner.And("click in the link esqueci minha senha");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table1.AddRow(new string[] {
                        "Email",
                        ""});
#line 8
    testRunner.And("fill fields with following data", ((string)(null)), table1);
#line 11
 testRunner.When("click in the button resetar senha");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table2.AddRow(new string[] {
                        "Email",
                        "\'Email\' deve ser preenchido."});
#line 12
 testRunner.Then("should show the following error messages", ((string)(null)), table2);
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Try to reset password with invalid email")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User should be able to get a new password")]
        public virtual void TryToResetPasswordWithInvalidEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Try to reset password with invalid email", new string[] {
                        "ResetForEachTest"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("navigate to \'\'");
#line 19
 testRunner.And("click in the link login");
#line 20
 testRunner.And("click in the link esqueci minha senha");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table3.AddRow(new string[] {
                        "Email",
                        "notfound@gmail.com"});
#line 21
    testRunner.And("fill fields with following data", ((string)(null)), table3);
#line 24
 testRunner.When("click in the button resetar senha");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table4.AddRow(new string[] {
                        "Email",
                        "\'Email\' não cadastrado."});
#line 25
 testRunner.Then("should show the following error messages", ((string)(null)), table4);
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Try to reset password with valid email")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User should be able to get a new password")]
        public virtual void TryToResetPasswordWithValidEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Try to reset password with valid email", new string[] {
                        "ResetForEachTest"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("navigate to \'\'");
#line 32
 testRunner.And("click in the link login");
#line 33
 testRunner.And("click in the link esqueci minha senha");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table5.AddRow(new string[] {
                        "Email",
                        "abcd@gmail.com"});
#line 34
    testRunner.And("fill fields with following data", ((string)(null)), table5);
#line 37
 testRunner.When("click in the button resetar senha");
#line 38
 testRunner.Then("should show text \'Uma nova senha foi enviada para o email indicado.\' at \'h2\'");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
